version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - touch hello.txt
      - mv buildspec2.yml buildspec.yml
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
