version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cat hello.txt
  post_build:
    commands:
      - echo Build completed on `date`
